# Site settings
title: 阿J小虫
subtitle: 阿J小虫's博客
description: 阿J小虫's博客
production_url : http://ichatter.cn
# cdn_url : http://yblog.b0.upaiyun.com
encoding: utf-8

author :
  name : yzy
  email : henry.yang86@gmail.com
#  github : yzy
#  twitter : yzy

# Build settings
safe: false
timezone: Asia/Shanghai
markdown: kramdown
gems: [jekyll-paginate]


# permalink
permalink: /:title.html

JB :
  version : 0.3.0

  BASE_PATH : false
  ASSET_PATH : false
  IMAGE_PATH : false

  categories_path : /categories.html
  tags_path : /tags.html
  guestbook_path : /guestbook.html
  about_path : /about.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : duoshuo
    duoshuo :
      short_name : yzy
      top_threads_num : 5
      top_threads_range : monthly

  analytics :
    provider : google_baidu
#    baidu :
#      tracking_id : 'c172b7087a2b6b62acb6057bb733a8ea'
#    google :
#      tracking_id : 'UA-12599330-12'
